define(['kendo'],
    function(kendo){
        'use strict';
        return {
            shipmentHeader:{
                id:"id",
                fields: {
                    id: {type:"number", editable: false, nullable: true },
                    tenantId:{type: "number"},
                    warehouseId:{type: "number",editable:false,nullable:false},
                    cargoOwnerId:{type: "number"},
                    orderId:{type: "number"},
                    invoiceId:{type: "number"},
                    datasourceCode:{type: "string"},
                    fromtypeCode:{type: "string"},
                    waveId:{type: "number"},
                    waveSeq:{type: "string"},
                    statusCode:{type: "string"},
                    referNo:{type: "string"},
                    deliveryTime:{type: "string"},
                    totalCategoryQty:{type: "number"},
                    totalQty:{type: "number"},
                    totalNetweight:{type: "number"},
                    totalGrossweight:{type: "number"},
                    totalVolume:{type: "number"},
                    expressName:{type: "string"},
                    expressNo:{type: "string"},
                    vehicleNo:{type: "string"},
                    expressTypeCode:{type: "string"},
                    containerNo:{type: "string"},
                    picker:{type: "string"},
                    isPrintExpress:{type: "boolean" ,editable: true, nullable: true},
                    isPrintDelivery:{type: "boolean" ,editable: true, nullable: true},
                    isPrintPicking:{type: "boolean" ,editable: true, nullable: true},
                    isPrintInvoice:{type: "boolean" ,editable: true, nullable: true},
                    printExpressUser:{type: "string"},
                    printExpressTime:{type: "string"},
                    isCancelled:{type: "boolean" ,editable: true, nullable: true},
                    isClosed:{type: "boolean" ,editable: true, nullable: true},
                    totalWeight:{type: "number"},
                    allocateStatuscode:{type: "string"},
                    pickStatuscode:{type: "string"},
                    checkStatuscode:{type: "string"},
                    packageStatuscode:{type: "string"},
                    weightStatuscode:{type: "string"},
                    handoverStatuscode:{type: "string"},
                    deliveryStatuscode:{type: "string"},
                    isEwaybillFinished:{type: "boolean" ,editable: true, nullable: true},
                    logisticAreaName:{type: "string"},
                    defaultZoneNo:{type: "string"},
                    defaultLocationNo:{type: "string"},
                    cartongroupCode:{type: "string"},
                    remark:{type: "string"},
                    createUser: { type: "string" },
                    createTime: { type: "string" },
                    updateUser: { type: "string" },
                    updateTime: { type: "string" },
                    isUrgent: {type:"boolean",defaultValue:false},
                    invoiceTypeCode: {type:"string",defaultValue:false },
                    order:{type:""},
                    isPrintsku:{type:"boolean",defaultValue:false},
                }
            },


            shipmentDetail:{
                id:"id",
                fields: {
                    id:{type: "number",editable:false,nullable:false},
                    shipmentId:{type: "number"},
                    tenantId:{type: "number"},
                    saleOrderNo:{type: "string"},
                    referNo:{type: "string"},
                    skuId:{type: "number"},
                    sku:{type: "string"},
                    skuName:{type: "string"},
                    skuBarcode:{type: "string"},
                    storageRoomId:{type: "string"},
                    inventoryStatusCode:{type: "string"},
                    zoneTypeCode:{type: "string"},
                    zoneId:{type: "number"},
                    locationId:{type: "number"},
                    palletNo:{type: "string"},
                    containerNo:{type: "string"},
                    orderedQty:{type: "number"},
                    allocatedQty:{type: "number"},
                    pickedQty:{type: "number"},
                    shippedQty:{type: "number"},
                    grossWeight:{type: "number"},
                    netWeight:{type: "number"},
                    volume:{type: "number"},
                    description:{type: "string"},
                    amount:{type: "number"},
                    price:{type: "number"},
                    discountAmount:{type: "number"},
                    promotionAmount:{type: "number"},
                    actualPayment:{type: "number"},
                    isGift:{type: "boolean" ,defaultValue:false},
                    workGroupNo:{type: "number"},
                    createUser: { type: "string" },
                    createTime:{type: "number"},
                    updateUser: { type: "string" },
                    updateTime:{type: "number"},
                    isCanceled:{type: "boolean" ,defaultValue:false}
                }
            }
        };
    });