define(['kendo'],
    function(kendo){
        'use strict';
        return {
            unfrozenHeader:{
                id:"id",
                fields: {
                    id: {type: "number", editable: false, nullable: true},
                    frozenId:{type:"number"},
                    tenantId: {type: "number"},
                    warehouseId: {type: "number", editable: false, nullable: false},
                    cargoOwnerId: {type: "number"},
                    name: {type: "string"},
                    factoringType: {type: "string"},
                    statusCode: {type: "string"},
                    totalQty: {type: "number"},
                    totalCartonQty: {type: "number"},
                    totalAmount: {type: "number"},
                    totalNetWeight: {type: "number"},
                    totalGrossWeight: {type: "number"},
                    totalVolume: {type: "number"},
                    factoringTotalQty:{type:"number"},
                    factoringOrganizeId: {type: "number"},
                    factoringTime: {type: "number"},
                    factoringActualTime:{type:"number"},
                    auditedOrganizeId: {type: "string"},
                    auditedUser: {type: "string"},
                    auditedTime: {type: "string"},
                    isAudited: {type: "boolean", defaultValue: true},
                    isInvalided: {type: "boolean", defaultValue: false},
                    createUser: {type: "string"},
                    createTime: {type: "string"},
                    updateUser: {type: "string"},
                    updateTime: {type: "string"},
                    isCancelled: {type: "boolean", defaultValue: false},
                    isDel: {type: "boolean", defaultValue: false},
                    description: {type: "string"}
                }
            },
            unfrozenDetail:{
                id:"id",
                fields: {
                    id:{type: "number",editable:false,nullable:false},
                    unfrozenId:{type: "number"},
                    frozenDetailId:{type:"number"},
                    tenantId:{type: "number"},
                    warehouseId:{type: "number"},
                    skuId:{type: "number"},
                    sku:{type: "string"},
                    skuName:{type: "string"},
                    skuBarcode:{type: "string"},
                    workGroupNo:{type: "number"},
                    locationId:{type: "number"},
                    storageRoomId:{type: "number"},
                    palletNo:{type: "string"},
                    containerNo:{type: "string"},
                    factoringQty:{type: "number"},
                    netWeight:{type: "number"},
                    grossWeight:{type: "number"},
                    volume:{type: "number"},
                    description:{type: "string"},
                    costPrice:{type: "number"},
                    totalPrice:{type: "number"},
                    categorysId:{type: "number"},
                    spec:{type: "string"},
                    factoringStatusCode:{type:"string"},
                    statusCode: {type: "string"},
                    unitType:{type: "string"},
                    createUser: { type: "string" },
                    createTime:{type: "number"},
                    updateUser: { type: "string" },
                    updateTime:{type: "number"},
                    frozenQty:{type:"number"},
                    unfrozenedQty:{type:"number"},
                }
            }
        };
    });

