define(['kendo'],
    function (kendo) {
        'use strict';
        return {
            receiptHeader:{
                id:"id",
                fields:{
                    id:{type: "number",editable:false,nullable:false},
                    tenantId:{type: "number"},
                    warehouseId:{type: "number",editable:false,nullable:false},
                    asnId:{type:"number"},
                    cargoOwnerId:{type: "number"},
                    fromTypeCode:{type: "string"},
                    datasourceCode:{type:"string"},
                    receiptDate:{type: "number"},
                    originNo:{type: "number"},
                    totalQty:{type: "number"},
                    totalPalletQty:{type: "number"},
                    totalCartonQty:{type: "number"},
                    totalNetWeight:{type: "number"},
                    totalGrossWeight:{type: "number"},
                    totalVolume:{type: "number"},
                    receiptUser:{type: "string"},
                    qcInspector:{type: "string"},
                    description:{type:"string"},
                    statusCode:{type: "string"},
                    receiptStatusCode:{type:"string"},
                    createUser:{type: "string"},
                    createTime:{type: "number"},
                    updateUser:{type: "string"},
                    updateTime:{type: "number"},
                    auditedUser:{type: "string"},
                    auditedTime:{type: "number"},
                    receiptTypeCode:{type: "string"},
                    isDel:{type: "boolean"},
                    version:{type: "number"},
                    fromOrderNo:{type: "number"},
                    fromOmsNo:{type: "number"},
                }
            },

            receiptDetail:{
                id:"id",
                fields: {
                    id:{type: "number",editable:false,nullable:false},
                    receiptId:{type: "number"},
                    tenantId:{type: "number"},
                    asnDetailId:{type: "number"},
                    warehouseId:{type: "number"},
                    skuId:{type: "number"},
                    sku:{type: "string"},
                    skuName:{type: "string"},
                    skuBarcode:{type:"string"},
                    workGroupNo:{type: "string"},
                    locationId:{type: "number"},
                    storageRoomId:{type: "number"},
                    palletNo:{type: "string"},
                    containerNo:{type: "string"},
                    receivedQty:{type: "number"},
                    receiptTime:{type: "string"},
                    netWeight:{type:"number"},
                    grossWeight:{type:"number"},
                    volume:{type:"number"},
                    isDel:{type: "boolean"},
                    inventoryStatusCode:{type: "string"},
                    description:{type: "string"},
                    costPrice:{type:"number"},
                    totalPrice:{type:"number"},
                    categorysId:{type:"number"},
                    spec:{type:"string"},
                    property:{type:"string"},
                    unitType:{type:"string"},
                    warehouseTemp:{type:"number"},
                    transportTemp:{type:"number"},
                    createUser:{type: "string"},
                    createTime:{type: "number"},
                    updateUser:{type: "string"},
                    updateTime:{type: "number"},
                    version:{type: "number"},
                }
            }
        };
    });